### ISSUE TITLE
Channel ID not being read from .env : Ubuntu Oracle Cloud hosted service

### ISSUE THREAD

**Issue by welpdnd** [holmityd/GitHub-Issues-Discord-Threads-Bot#125]
Hi,

Thanks for writing this up, much appreciated.

I've managed to get this working on a free Oracle Cloud VM. Unfortunately on npm run dev I get the error below. It appears to be trying to use a different channel ID to the one I input to the config file - even changing it to a dummy value has it revert to the channel ID below. I have tried to search for references to the channel ID below but no luck. 

```
Server is running on port 5000
06-09 16:19:25 Logged in as GitHubIssues#6541!
06-09 16:19:25 Issues loaded : 7
/home/ubuntu/discordBot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148
                        throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);
                              ^


DiscordAPIError[10003]: Unknown Channel
    at handleErrors (/home/ubuntu/discordBot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.runRequest (/home/ubuntu/discordBot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)
    at SequentialHandler.queueRequest (/home/ubuntu/discordBot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)
    at _REST.request (/home/ubuntu/discordBot/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)
    at async ChannelManager.fetch (/home/ubuntu/discordBot/node_modules/discord.js/src/managers/ChannelManager.js:123:18) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Unknown Channel', code: 10003 },
  code: 10003,
  status: 404,
  method: 'GET',
  url: 'https://discord.com/api/v10/channels/1249342558606332075'

```

**Comment by holmityd** [comment]
Hi

I've updated the readme to include instructions for retrieving the channel ID for the .env file [here](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot?tab=readme-ov-file#env). Now, there are no placeholder values for the channel ID, ensuring that it's fetched directly from the .env file during runtime.

Let me know if you need further clarification or assistance

**Comment by holmityd** [comment]
![image](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/6e43dd25-2fe3-47f7-82e0-a4170ef4261e)
https://discord.com/channels/<GUILD_ID>/<DISCORD_CHANNEL_ID>

**Comment by welpdnd** [comment]
Thank you for taking the time to investigate, respond and update so quickly, I really appreciate it - I spent about 5 hours trying all sorts to get it to work yesterday!

Unfortunately even with the new build I am still getting the same error with the same incorrect channel ID being used. It seems to be similar to what this user is reporting in: https://stackoverflow.com/questions/69218176/env-file-not-updating-in-local-environment-in-react-js

It seems like my local node installation might be faulty or have a broken cache. Even after reinstalling and purging any local node data, I am getting the same error message. I am pretty sure it is a local or user issue but if you have any other suggestions to troubleshoot, that would be great, otherwise I'll update this ticket with any progress.

**Comment by welpdnd** [comment]
Here's an example. The Discord token is picked up fine and the bot appears online locally but the wrong channel ID is being used, somehow! The ID on the right hand side is the correct one.
![channelid](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/163332443/1a9dab18-c72c-47f8-9ffe-e3e312653c59)

**Comment by holmityd** [comment]
src/discord/discordHandlers.ts after line 46
```js
logger.info(`Issues loaded : ${store.threads.length}`);
``` 
add 
```js
console.log("DISCORD_CHANNEL_ID", config.DISCORD_CHANNEL_ID);
```

then run dev, before error must log id
![image](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/bb2e136c-9325-4c39-88ee-7dda2b37da72)

**Comment by welpdnd** [comment]
Thanks for looking into this. Let me know if you have a tip jar link somewhere for a small thank you for your time.

The log outputs the correct channel ID, which indicates the .env file is being used correctly, but the script still uses the incorrect value on the GET. I have no idea what to think at this point 😄 . I tried deleting and recreating the bot, Discord server, channel, tokens etc. just in case that channel ID was encoded somewhere but I got the same result.

![Screenshot 2024-06-10 133717](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/163332443/3f33321a-c0ac-4f62-941f-747bc43c8163)

**Comment by holmityd** [comment]
if id same in .env file then idk, maybe bot dont have rights to see this channel, kick bot, reinvite with admin access link
https://discord.com/developers/applications/

![image](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/29ca2afe-7c6f-4a41-895a-0cc5f602bd5d)

**Comment by welpdnd** [comment]
Cheers, attempted all that and got the same error unfortunately. 

The issue appears to be that the GET request is pointing to a channel ID that does not exist. It's possible this was the very first channel ID I used on my local system which has now been cached somewhere. The fact it is so persistent on a single variable is very confusing 😄 I can change the other variables (Discord token, GitHub token etc.) and have them update fine. 

I will try this on a different PC or VM and see if it makes any difference.

**Comment by holmityd** [comment]
comment that part: 
![image](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/8d3ba587-a179-4c29-a2bd-7740a1812705)

and try create new thread, if logs in terminal then good, if nothing happens then

**Comment by holmityd** [comment]
src/discord/discordHandlers.ts after line 53 add
```js
console.log("handleThreadCreate", params.parentId);
```
![image](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/9de801b8-4a55-4bac-b301-c33ddab218d3)

after that on every new thread create will log channel id

![image](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/df76d2bf-6e42-4955-8556-5e148039c201)

1st id comes from .env file
2nd from discord bot when creating new thread, or even creating new msg in other channels, so check in not busy server

**Comment by welpdnd** [comment]
Thanks. Unfortunately the script is still erroring at the same stage so the event for the handeThreadCreate log item never appears. The correct thread ID is being gathered from .env but the incorrect ID is being used to call the Discord API. 
![Screenshot 2024-06-10 160111](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/163332443/f18d8c1e-878e-4817-806c-c116f0337d15)

It persists regardless of where I run it on my local machine, and even remotely on my VM. I figure I am incorrectly using the code - though I did manage to get it working at the start! 

I am wondering if I should try to hard code my Discord channel ID in the ts scripts themselves? Then at least I can try to force it to point to the right location. [](url)

**Comment by holmityd** [comment]
Something wrong with terminal, its calling for someother channel_id, maybe kill all tasks (or just restart). And edited code part not same as in terminal i think, change console.log("DISCORD_CHANNEL_ID" to something else, for example console.log("TEST_DISCORD_CHANNEL_ID", guessing that from commented part, cus only this pa
rt fetching channel id which causing that error. But in pic channel ids different, idk where they comes from, they must be same

![Безымянный](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/6c11075d-9389-4aa8-8dfb-c1f93973ab8b)

**Comment by holmityd** [comment]
comment that part too:
![image](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/52883148/4bc0db57-565d-4f16-9761-58a850319b77)

**Comment by holmityd** [comment]
if after that works, clear all issues on github issues page, and restore all changes

**Comment by holmityd** [comment]
yep, reproduced problem: github issue created with bot, bot turned off, discord thread deleted, github issue still there, code fetching all issues with regex /https:\/\/discord\.com\/channels\/(\d+)\/(\d+)\/(\d+)(?=\))/ , then tryes to sync with discord thread part, but its not there so gives error, my bad, didn't see on prev pic ids not same

**Comment by welpdnd** [comment]
> comment that part too: ![image](https://private-user-images.githubusercontent.com/52883148/338257759-4bc0db57-565d-4f16-9761-58a850319b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzUyMzQsIm5iZiI6MTcxODAzNDkzNCwicGF0aCI6Ii81Mjg4MzE0OC8zMzgyNTc3NTktNGJjMGRiNTctNTY1ZC00ZjE2LTk3NjEtNThhODUwMzE5Yjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE1NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNWI3Yjg1M2MyODI2MjliZDgxMDg2ZGJlY2Y3ZmQ3OWQ1NzQ1M2IwYzIwZTkyMjZkMTNmN2JlYzcyN2VjZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y-diUq162vhIxAkSSXRWeACQ-HJTLZ4iRppiKHT8yks)

This worked! 
![Screenshot 2024-06-10 172029](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/163332443/e8bfd3bd-a309-4116-970b-1b6d51de77df)

![threadid](https://github.com/holmityd/GitHub-Issues-Discord-Threads-Bot/assets/163332443/4edc5a9f-d347-4abd-aef7-2f2fe7dac558)

**Comment by holmityd** [comment]
yep, for now solution clear all github issues which created by bot, and dont delete post in discord without deleting it from github (bot will auto do that, but if off need manually delete), later will fix that to skip that issues while listing

**Comment by welpdnd** [comment]
Thank you so much for all your time today, this will be a huge benefit to my team. If you have a tip jar then just let me know!

**Comment by holmityd** [comment]
nah, you welcome, thanks for reporting that bug
